CREATE TABLE resultado_actividad (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    estudiante_id BIGINT NOT NULL,

    actividad_id BIGINT NOT NULL,

    puntaje INTEGER NOT NULL,

    cantidad_correctas INTEGER NOT NULL,

    cantidad_incorrectas INTEGER NOT NULL,

    porcentaje DECIMAL(5,2) NOT NULL,

    duracion_segundos INTEGER NOT NULL,

    estado VARCHAR(30) NOT NULL,

    errores JSONB NOT NULL,

    fecha_realizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_resultado_estudiante
        FOREIGN KEY (estudiante_id)
        REFERENCES estudiante(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_resultado_actividad
        FOREIGN KEY (actividad_id)
        REFERENCES actividad(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_resultado_puntaje
        CHECK (puntaje BETWEEN 0 AND 100),

    CONSTRAINT chk_resultado_porcentaje
        CHECK (porcentaje BETWEEN 0 AND 100),

    CONSTRAINT chk_resultado_correctas
        CHECK (cantidad_correctas >= 0),

    CONSTRAINT chk_resultado_incorrectas
        CHECK (cantidad_incorrectas >= 0),

    CONSTRAINT chk_resultado_duracion
        CHECK (duracion_segundos >= 0)

);

CREATE INDEX idx_resultado_estudiante
ON resultado_actividad(estudiante_id);

CREATE INDEX idx_resultado_actividad
ON resultado_actividad(actividad_id);

CREATE INDEX idx_resultado_estudiante_fecha
ON resultado_actividad(estudiante_id, fecha_realizacion DESC);